# Generated by Django 3.2.9 on 2021-11-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkResApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='slot',
            field=models.IntegerField(),
        ),
    ]
