# Generated by Django 3.2.9 on 2021-11-30 19:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParkResApp', '0003_parking_parkswitch'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotA',
            fields=[
                ('LotAId', models.AutoField(primary_key=True, serialize=False)),
                ('space', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
                ('takenBool', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkResApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='LotB',
            fields=[
                ('LotBId', models.AutoField(primary_key=True, serialize=False)),
                ('space', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
                ('takenBool', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkResApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='LotC',
            fields=[
                ('LotCId', models.AutoField(primary_key=True, serialize=False)),
                ('space', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
                ('takenBool', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkResApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='LotD',
            fields=[
                ('LotDId', models.AutoField(primary_key=True, serialize=False)),
                ('space', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
                ('takenBool', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParkResApp.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='messages',
            name='parkingId',
        ),
        migrations.DeleteModel(
            name='Parking',
        ),
    ]
