# Generated by Django 3.2.9 on 2021-11-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkResApp', '0002_alter_parking_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='parkSwitch',
            field=models.BooleanField(default=True),
        ),
    ]
